#!/bin/bash

onefile(){
filepath=$2
classname=$(basename "$filepath")
if [ -z "$3" ]
then
    classname="${classname%.*}"
else

if [ $3 = "-a" ]; then
   args=("${@:4}")   
   classname="${classname%.*}"
   else
       classname=$3
       args=("${@:5}")  
fi

fi
echo "----------------------------------"
if [ ${#filepath} -eq 0 ]
then
echo "Error: No file input"
else
javac $filepath
cd $(dirname "$filepath")
java $classname $args
fi
echo 
echo "----------------------------------"
echo "Process exited! Done."
}

multifile(){
if [ $4 = "-a" ]; then
   args=("${@:5}")   
fi
   
projectpath=$2
classname=$3

class=$classname
OIFS="$IFS"
IFS='.' array=($class)
IFS="$OIFS"
pathlength=${#array[*]}
i=${0}

subpath=""

for (( i=0; i < $pathlength-1; i++ )); do
 subpath=${subpath}${array[i]}"/";
done
cd $projectpath
echo "----------------------------------"

if [ -z "$2" ]
then
    echo "Error: No class input"
    echo "----------------------------------"
    exit
fi

if [ -z "$1" ]
then
echo "Error: No file input"
echo "----------------------------------"
exit
fi
javac -sourcepath . ${subpath}/*.java
java -classpath . $classname  $args

echo 
echo "----------------------------------"
echo "Process exited! Done."
}


while getopts ":fpa:" opt; do
  case $opt in
    f) 
     onefile $@
      ;;
    p) 
     multifile $@
      ;;
    \?)
      echo "Invalid option: -$OPTARG" >&2
      exit 1
      ;;
    :)
      echo "Option -$OPTARG requires an argument." >&2
      exit 1
      ;;
  esac
done

shift "$(($OPTIND -1))"

